### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by thevoiddancer** [VRGhost/pytest-flake8#16]
So the old pytest-flake8 is abandoned, and looking at this error (https://github.com/PyCQA/flake8/issues/367) got me to this project. However, that specific error persists, and there's actually TWO open issues here about it (https://github.com/VRGhost/pytest-flake8/issues/15 and https://github.com/VRGhost/pytest-flake8/issues/13). The last commit was over a year ago.

So can we conclude that this project is abandoned and that we need another fork of pytest-flake8?

**Comment by VRGhost** [comment]
Hey.
It is, in effect. As I have moved to more up-to-date qc tools (`ruff` is great in particular).

I'm happy to give you access to maintain it if you're up to it.
