### ISSUE TITLE
Ignoring pyproject.toml file

### ISSUE THREAD

**Issue by MReinisch** [VRGhost/pytest-flake8#7]
Currently i'm porting my projects over to use only the `pyproject.toml` file for configuration.

Pytest is supporting this but flake8 not.

Maybe it is possible to add a check if the file extension of `config.getini("flake8-config")` is `.toml` and ignore it then.

Normaly the toml file will be parsed without an error but if you have something like this in it there will be an exception.

```
[[tool.mypy.overrides]]
module = "moduleA.*"
ignore_missing_imports

[[tool.mypy.overrides]]
module = 'moduleB.*'
ignore_errors = true
```

```
FLAKE8 - configparser.DuplicateSectionError: While reading from '/src/pyproject.toml' [line 29]: section '[tool.mypy.overrides]' already exists
```

If you need special settings for flake8 you can still specify with `flake8-config` a config file that will be readed unless it is a `toml`

**Comment by VRGhost** [comment]
Good point.

Try setting "flake8-config" param to an empty string in the meantime. This should squelch the error.

I think that the syntax'd be

`flake8-config = `

**Comment by MReinisch** [comment]
Works with this in the `toml`:
```flake8-config = ""```

**Comment by VRGhost** [comment]
Oh, wow. GH automatically closes these.

Anyway, I've just pushed out the 1.2.1 that should add the suggested fix.  Can you please confirm if it works for you.

**Comment by MReinisch** [comment]
Works like a charm, thx for the fast fix.
